id: P009523
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17336
  title: ཉི་གཞོན་འཆར་ཁ་མ་དང་སྨན་བླ།
  author: ''
  volumes:
    b7e413fc8e3546b0b9732483c81be84c:
      image_group_id: I8LS17343
      title: ''
      volume_number: 1
      total_pages: 168
      base_file: v001.txt
